#!/usr/bin/env bash

#Copyright (C) 2013 Niklas Thorne.
#
#This file is part of again.
#
#again is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#again is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with again.  If not, see <http://www.gnu.org/licenses/>.

readonly SED_DATE_RE="[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}"
readonly BASH_DATE_RE="[0-9]{4}-[0-9]{2}-[0-9]{2}"
readonly DATE_FORMAT="%Y-%m-%d"

function usage()
{
  echo " again add-on:"
  echo "   again N"
  echo "     mark N as complete and recreate with any due date set as today."
  echo "   again N DAYS"
  echo "     mark N as complete and recreate with any due date and deferral date"
  echo "     set as DAYS days from today."
  echo "   again N +DAYS"
  echo "     mark N as complete and recreate with any due date and deferral date"
  echo "     set as DAYS days from their original values."
  echo ""
  exit
}

function error()
{
  echo "error: $@" >&2
  exit 1
}

function parse_options()
{
  local action=$1
  shift

  [ "$action" = "usage" ] && usage

  # Retrieve the item number from the arguments
  ITEM=$1
  if [[ ! "$ITEM" =~ ^[0-9]+$ ]]
  then
    error "$ITEM: invalid item number"
  exit
  fi

  shift
  DAYS=$1
}

# Determine which date implementation is installed on this machine
function determine_date_version()
{
  date -v 1d 1>/dev/null 2>/dev/null

  # BSD flavor accepts the -v (value) option without complaint
  if [[ 0 -eq $? ]]
  then
    DATE_VERSION="BSD"

  # GNU flavor says so in the --version output  
  elif [[ $(date --version) =~ GNU ]]
  then
    DATE_VERSION="GNU"

  # else not supported  
  else
    error "Unknown date implementation. Bailing out."

  fi
}

# Set $TODAY to today's date
function today()
{
  if [[ $DATE_VERSION == "BSD" || $DATE_VERSION == "GNU" ]]
  then
    TODAY=`date +$DATE_FORMAT`
  else
    error "Unknown date implementation. Bailing out."
  fi
}

# Retrieve line number $ITEM from the file $TODO_FILE
function get_line()
{
  [ -f "$TODO_FILE" ] || error "$TODO_FILE: no such file"
  # Get the line from the todo file
  LINE=$(sed "$ITEM!d" "$TODO_FILE")
  [ -z "$LINE" ] && error "$ITEM: no such line"
}

# Adjust $ORIGINAL by $DAYS, store in $NEW_DATE
function adjust_date()
{
  if [[ $DATE_VERSION == "GNU" ]]
  then
    NEW_DATE=`date -d "$ORIGINAL $DAYS days" +$DATE_FORMAT`
  elif [[ $DATE_VERSION == "BSD" ]]
  then
    NEW_DATE=`date -j -v"$DAYS"d -f $DATE_FORMAT $ORIGINAL +$DATE_FORMAT`
  else
    error "Unknown date implementation. Bailing out."
  fi
}

# Replace any creation date of the item in $LINE to $TODAY
function replace_creation_date()
{
  if [[ "$LINE" =~ ^(\([A-Z]\) )*$BASH_DATE_RE.* ]]
  then
    LINE=$(echo "$LINE" | sed "s/^\(([A-Z]) \)*\($SED_DATE_RE \)*\(.*\)/\1$TODAY \3/")
  fi
}

# Replace any date with $TAG in $LINE by $DAYS
function replace_tagged_date()
{
  if [[ "$LINE" =~ .*$TAG:$BASH_DATE_RE.* ]]
  then
    if [[ -z $DAYS ]]
    then
      # DAYS not detailed; adjust to today.
      NEW_DATE=$TODAY
    else
      if [[ "$DAYS" =~ ^\+[0-9]+ ]]
      then
        # Adjust to DAYS from original values.
        ORIGINAL=$(echo "$LINE" | sed "s/.*$TAG:\($SED_DATE_RE\).*/\1/")
      else
        # Adjust to DAYS from today.
        ORIGINAL=$TODAY
      fi
      adjust_date
    fi
    LINE=$(echo "$LINE" | sed "s/\(.*$TAG:\)\($SED_DATE_RE\)\(.*\)/\1$NEW_DATE\3/")
  fi
}

# Replace any due date (due:DATE) of the item in $LINE by $DAYS
function replace_due_date()
{
  TAG=due
  replace_tagged_date
}

# Replace any deferral date (t:DATE) of the task in $LINE by $DAYS
function replace_deferral_date()
{
  TAG=t
  replace_tagged_date
}

parse_options "$@"
determine_date_version
today
get_line
replace_creation_date
replace_due_date
replace_deferral_date

if [[ "$LINE" != "" ]]
then
  "$TODO_FULL_SH" command do "$ITEM"
  "$TODO_FULL_SH" command add "$LINE"
fi

